import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const createHomeStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  fullscreenContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  fullscreenVideo: {
    width: '100%',
    height: '100%',
  },
  videoControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 2,
    marginHorizontal: 10,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#DC143C',
    borderRadius: 2,
  },
  timeText: {
    color: '#fff',
    fontSize: 12,
    minWidth: 40,
  },
  controlButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
  },
  controlButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopButton: {
    backgroundColor: '#DC143C',
    flexDirection: 'row',
    width: 80,
    gap: 4,
  },
  stopButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  headerContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    alignItems: 'flex-end',
  },
  liveSection: {
    marginTop: 8,
    paddingBottom: 10,
  },
  liveSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  liveSectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 12,
  },
  programmedLiveContainer: {
    marginHorizontal: 16,
    marginBottom: 20,
  },
  liveCardFull: {
    height: height * 0.5,
    marginHorizontal: 16,
    overflow: 'hidden',
    backgroundColor: colors.card,
    borderRadius: 12,
  },
  liveImageFull: {
    width: '100%',
    height: '100%',
  },
  liveOverlayFull: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
  },
  liveTitleFull: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  liveViewers: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  liveViewersText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  liveCard: {
    width: width * 0.8,
    height: 200,
    marginLeft: 16,
    borderRadius: 16,
    overflow: 'hidden',
  },
  liveImage: {
    width: '100%',
    height: '100%',
  },
  liveOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  liveTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  liveBadge: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: '#DC143C',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  liveBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  section: {
    marginTop: 24,
  },
  sectionHeaderWithButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  // 🔥 NOUVEAUX STYLES MODERNES POUR "VOIR PLUS"
  modernSeeMoreButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -14,
  },
  seeMoreContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  seeMoreIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  modernSeeMoreText: {
    fontSize: 13,
    fontWeight: '600',
    marginRight: 4,
    color: '#DC143C',
  },
  // 🔥 FIN DES NOUVEAUX STYLES
  newsCard: {
    width: width * 0.75,
    height: 200,
    marginLeft: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  newsImage: {
    width: '100%',
    height: '100%',
  },
  newsOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  newsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DC143C',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginBottom: 8,
    gap: 4,
  },
  newsBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: 'bold',
  },
  newsTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  newsTime: {
    color: '#B0B0B0',
    fontSize: 11,
  },
  trendingCard: {
    width: 140,
    height: 180,
    marginLeft: 16,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  trendingImage: {
    width: '100%',
    height: 120,
  },
  trendingInfo: {
    padding: 10,
  },
  trendingTitle: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  trendingMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendingViews: {
    fontSize: 11,
  },
  videoCard: {
    width: 140,
    height: 180,
    marginLeft: 16,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  videoImage: {
    width: '100%',
    height: 120,
  },
  videoDuration: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  videoDurationText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  videoInfo: {
    padding: 10,
  },
  videoTitle: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  videoDate: {
    fontSize: 11,
  },
  programCard: {
    width: width * 0.8,
    height: 200,
    marginLeft: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  programImage: {
    width: '100%',
    height: '100%',
  },
  programOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  programTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  programTime: {
    color: '#B0B0B0',
    fontSize: 12,
  },
  interviewCard: {
    width: 200,
    height: 160,
    marginLeft: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  interviewImage: {
    width: '100%',
    height: '100%',
  },
  interviewOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
  },
  interviewBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DC143C',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginBottom: 8,
    gap: 4,
  },
  interviewBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: 'bold',
  },
  interviewTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  interviewGuest: {
    color: '#B0B0B0',
    fontSize: 11,
  },
  noLiveContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: colors.card,
    height: height * 0.4,
  },
  noLiveText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 8,
  },
  noLiveSubtext: {
    fontSize: 12,
    textAlign: 'center',
  },
  emptyStateHorizontal: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    marginLeft: 16,
  },
  emptyStateText: {
    fontSize: 12,
    marginTop: 12,
  },
  archiveBanner: {
    marginHorizontal: 16,
    padding: 20,
    backgroundColor: 'rgba(255, 215, 0, 0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.2)',
  },
  archiveBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  archiveIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  archiveTextContainer: {
    flex: 1,
  },
  premiumBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    gap: 4,
  },
  premiumBadgeTextSmall: {
    color: '#FFD700',
    fontSize: 11,
    fontWeight: 'bold',
  },
  archiveCard: {
    width: width * 0.7,
    height: 200,
    marginLeft: 16,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.card,
  },
  archiveImage: {
    width: '100%',
    height: '100%',
  },
  archiveOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
  },
  archivePremiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 8,
    gap: 4,
  },
  archivePremiumText: {
    color: '#FFD700',
    fontSize: 11,
    fontWeight: 'bold',
  },
  archivePriceText: {
    color: '#FFD700',
    fontSize: 10,
    fontWeight: '600',
  },
  archiveTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  archiveMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  archiveMetaText: {
    color: '#B0B0B0',
    fontSize: 11,
  },
  archiveMetaSeparator: {
    color: '#B0B0B0',
    fontSize: 11,
    marginHorizontal: 4,
  },
  archiveBannerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 4,
  },
  archiveBannerDescription: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  archiveBannerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC143C',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 8,
  },
  archiveBannerButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  contentContainer: {
    paddingTop: 8,
  },
  seeMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  seeMoreText: {
    color: '#DC143C',
    fontSize: 14,
    fontWeight: '600',
  },

  // Ajoutez ces styles à votre fichier homeStyles.js
endOfSectionIndicator: {
  paddingVertical: 8,
  paddingHorizontal: 16,
  alignItems: 'center',
  justifyContent: 'center',
},
endOfSectionText: {
  color: colors.primary,
  fontSize: 14,
  fontWeight: '600',
},
});