// Export de tous les styles
export { createHomeStyles } from './homeStyles';
export { createBreakingNewsStyles } from './breakingNewsStyles';
export { createJTandMagStyles } from './jtandMagStyles';
export { createReportagesStyles } from './reportagesStyles';
export { createReelStyles } from './reelStyles';
export { createArchiveStyles } from './archiveStyles';
export { createDivertissementStyles } from './divertissementStyles';
export { createLiveStyles } from './liveStyles';
export { createMoviesStyles } from './moviesStyles';
export { createNewsStyles } from './newsStyles';
export { createProfileStyles } from './profileStyles';
export { createProgramStyles } from './programStyles';
export { createPopularProgramsStyles } from './popularProgramsStyles';
export { createAuthStyles } from './authStyles';
export { createFavoritesStyles } from './favoritesStyles';
export { createSettingsStyles } from './settingsStyles';
export { createSupportStyles } from './supportStyles';
